var oCurrentTab=null,iNotificationTimeoutId=null,oOptions=null,oBkgPage=chrome.extension.getBackgroundPage();
function init(){var a={"view-css":viewCSS,"reload-css":reloadCSS,"disable-all-styles":disableAllStyles,"disable-inline-styles":disableInlineStyles,"disable-embedded-styles":disableEmbeddedStyles,"disable-linked-style-sheets":disableLinkedStyleSheets,"show-used-colors":showUsedColors,"show-passwords":showPasswords,"remove-maxlength-attributes":removeMaxlengthAttributes,"convert-select-elements-to-text-inputs":convertSelectElementsToTextInputs,"show-hidden-elements":showHiddenElements,"clear-radio-buttons":clearRadioButtons,
"enable-form-elements":enableFormElements,"convert-gets-to-posts":convertFormMethods,"convert-posts-to-gets":convertFormMethods,"view-images-information":viewImagesInformation,"hide-all-images":hideAllImages,"hide-background-images":hideBackgroundImages,"show-alt-text-note":showAltTextNote,"show-dimensions-note":showDimensionsNote,"show-paths-note":showPathsNote,"view-javascript":viewJavaScript,"view-generated-source":viewGeneratedSource,"display-ruler":displayRuler,"display-color-picker":displayColorPicker,
"topographic-view":topographicView,"remove-cookies":removeCookies,"display-window-size":displayWindowSize,"resize-320x480":resizeBrowser,"resize-640x480":resizeBrowser,"resize-480x800":resizeBrowser,"resize-800x600":resizeBrowser,"resize-1024x768":resizeBrowser,"resize-1280x800":resizeBrowser,"resize-1280x1024":resizeBrowser,"resize-1366x768":resizeBrowser,"resize-1440x900":resizeBrowser,"resize-1600x900":resizeBrowser,"custom-size":customSize,"validate-html":validateHTML,"validate-css":validateCSS,
"validate-links":checkLinks,"validate-feed":validateFeed,"validate-accessibility":validateAccessibility,"validate-local-html":validateLocalHTML,"validate-local-css":validateLocalCSS},b;for(b in a)$(b).onclick=a[b];chrome.tabs.getSelected(null,function(a){oCurrentTab=a;for(var b=document.getElementsByTagName("nav")[0].getElementsByTagName("li"),a=0,e=b.length;a<e;a++)b[a].onclick=function(){for(var a=0;a<b.length;a++)$(b[a].id).removeClass("current"),$(b[a].id.substr(4)).removeClass("current");$(this.id).addClass("current");
$(this.id.substr(4)).addClass("current");for(a=0;a<oBkgPage.aNavItems.length;a++)oBkgPage.oStorage.del(oBkgPage.aNavItems[a],oCurrentTab.id);oBkgPage.oStorage.add(this.id.substr(4),oCurrentTab.id)};for(var f=!1,a=0;a<oBkgPage.aNavItems.length;a++)if(e=$(oBkgPage.aNavItems[a]),oBkgPage.oStorage.into(oBkgPage.aNavItems[a],oCurrentTab.id)){$("tab-"+e.id).addClass("current");e.addClass("current");f=!0;break}f||($("tab-stylesheets").addClass("current"),$("stylesheets").addClass("current"));for(a=0;a<oBkgPage.aBoxItems.length;a++)oBkgPage.oStorage.into(oBkgPage.aBoxItems[a],
oCurrentTab.id)&&$(oBkgPage.aBoxItems[a]).addClass("activated")});oOptions=oBkgPage.retrieveOptions()}function viewCSS(){isSupportedURL()&&fileSchemeAllowed(!1)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"getCSS"},function(a){a.aEmbeddedCSS.length===0&&a.aExternalCSS.length===0?showNotification("NO STYLE SHEET FOUND","green"):oBkgPage.createTab("created-tabs/view-css.html",a)})}
function reloadCSS(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=null;chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"reloadCSS"},function(b){a=b.iCount?b.iCount+" LINKED CSS FILE"+(b.iCount>1?"S":"")+" RELOADED":"NO LINKED CSS FILE FOUND";showNotification(a,"green")})}}function disableAllStyles(){toggleFeature(this,"toggleAllStyles")}function disableInlineStyles(){toggleFeature(this,"toggleInlineStyles")}function disableEmbeddedStyles(){toggleFeature(this,"toggleEmbeddedStyles")}
function disableLinkedStyleSheets(){toggleFeature(this,"toggleLinkedStyleSheets")}function showUsedColors(){isSupportedURL()&&fileSchemeAllowed(!0)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"getUsedColors"},function(a){oBkgPage.createTab("created-tabs/show-used-colors.html",a)})}
function showPasswords(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=this,b=oBkgPage.getFeatureState(a.id,oCurrentTab.id),c=null;chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"showPasswords",bActivated:b},function(d){b?(oBkgPage.setFeatureState(a.id,oCurrentTab.id,b),a.removeClass("activated")):(d.iCount?(a.addClass("activated"),oBkgPage.setFeatureState(a.id,oCurrentTab.id,b),c=d.iCount+" PASSWORD"+(d.iCount>1?"S":"")+" SHOWN"):c="NO PASSWORD FIELD FOUND",showNotification(c,"green"))})}}
function removeMaxlengthAttributes(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=this,b=oBkgPage.getFeatureState(a.id,oCurrentTab.id),c=null;chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"removeMaxlengthAttributes",bActivated:b},function(d){b?(oBkgPage.setFeatureState(a.id,oCurrentTab.id,b),a.removeClass("activated")):(d.iCount?(a.addClass("activated"),oBkgPage.setFeatureState(a.id,oCurrentTab.id,b),c=d.iCount+" MAXLENGTH ATTRIBUTE"+(d.iCount>1?"S":"")+" REMOVED"):c="NO MAXLENGTH ATTRIBUTE FOUND",
showNotification(c,"green"))})}}function convertSelectElementsToTextInputs(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=null;chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"convertSelectElementsToTextInputs"},function(b){a=b.iCount?b.iCount+" SELECT ELEMENT"+(b.iCount>1?"S":"")+" CONVERTED":"NO SELECT ELEMENT FOUND";showNotification(a,"green")})}}
function showHiddenElements(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=null;chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"showHiddenElements"},function(b){a=b.iCount?b.iCount+" HIDDEN INPUT CONTROL"+(b.iCount>1?"S":"")+" SHOWN":"NO HIDDEN INPUT CONTROL FOUND";showNotification(a,"green")})}}
function clearRadioButtons(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=null;chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"clearRadioButtons"},function(b){a=b.iCount?b.iCount+" RADIO BUTTON"+(b.iCount>1?"S":"")+" CLEARED":"NO RADIO BUTTON FOUND";showNotification(a,"green")})}}
function enableFormElements(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=null;chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"enableFormElements"},function(b){a=b.iCount?b.iCount+" FORM ELEMENT"+(b.iCount>1?"S":"")+" ENABLED":"NO DISABLED OR READ-ONLY FORM ELEMENT FOUND";showNotification(a,"green")})}}
function convertFormMethods(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=null;chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"convertFormMethods",sElementId:this.id},function(b){a=b.iCount?b.iCount+" FORM"+(b.iCount>1?"S":"")+" CONVERTED":"NO FORM FOUND";showNotification(a,"green")})}}
function viewImagesInformation(){isSupportedURL()&&fileSchemeAllowed(!1)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"getImages"},function(a){a.aImages.length===0?showNotification("NO IMAGE FOUND","green"):oBkgPage.createTab("created-tabs/view-images-information.html",a)})}function hideAllImages(){toggleFeature(this,"hideAllImages")}function hideBackgroundImages(){toggleFeature(this,"hideBackgroundImages")}
function showAltTextNote(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=this,b=oBkgPage.getFeatureState(a.id,oCurrentTab.id);chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"showNote",sType:"alt",bActivated:b},function(){oBkgPage.setFeatureState(a.id,oCurrentTab.id,b);b?a.removeClass("activated"):a.addClass("activated")})}}
function showDimensionsNote(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=this,b=oBkgPage.getFeatureState(a.id,oCurrentTab.id);chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"showNote",sType:"dimensions",bActivated:b},function(){oBkgPage.setFeatureState(a.id,oCurrentTab.id,b);b?a.removeClass("activated"):a.addClass("activated")})}}
function showPathsNote(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=this,b=oBkgPage.getFeatureState(a.id,oCurrentTab.id);chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"showNote",sType:"paths",bActivated:b},function(){oBkgPage.setFeatureState(a.id,oCurrentTab.id,b);b?a.removeClass("activated"):a.addClass("activated")})}}
function viewJavaScript(){isSupportedURL()&&fileSchemeAllowed(!1)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"getJavaScript"},function(a){a.aEmbeddedScripts.length===0&&a.aExternalScripts.length===0?showNotification("NO SCRIPT FOUND","green"):oBkgPage.createTab("created-tabs/view-javascript.html",a)})}
function viewGeneratedSource(){isSupportedURL()&&fileSchemeAllowed(!0)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"getGeneratedSource"},function(a){oBkgPage.createTab("created-tabs/view-source.html",a)})}
function displayRuler(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=this,b=oBkgPage.getFeatureState(a.id,oCurrentTab.id);chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"displayRuler",bActivated:b},function(){oBkgPage.setFeatureState(a.id,oCurrentTab.id,b);b?a.removeClass("activated"):(a.addClass("activated"),window.close())})}}
function displayColorPicker(){if(isSupportedURL()&&fileSchemeAllowed(!1)){var a=this,b=oBkgPage.getFeatureState(a.id,oCurrentTab.id);chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"displayColorPicker",bActivated:b},function(){oBkgPage.setFeatureState(a.id,oCurrentTab.id,b);b?a.removeClass("activated"):(a.addClass("activated"),window.close())})}}
function topographicView(){if(isSupportedURL()&&fileSchemeAllowed(!0)){var a=this,b=oBkgPage.getFeatureState(a.id,oCurrentTab.id);chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"topographicView",bActivated:b},function(){oBkgPage.setFeatureState(a.id,oCurrentTab.id,b);b?a.removeClass("activated"):a.addClass("activated")})}}
function removeCookies(){chrome.cookies.getAll({url:oCurrentTab.url},function(a){var b=null,b=0,c;for(c in a)chrome.cookies.remove({url:oCurrentTab.url,name:a[c].name}),b++;showNotification(b?b+" COOKIE"+(b>1?"S":"")+" REMOVED":"NO COOKIE FOUND ON CURRENT SITE","green")})}
function displayWindowSize(){isSupportedURL()&&fileSchemeAllowed(!0)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"getWindowSize"},function(a){showNotification("WINDOW: "+a.outerWidth+" x "+a.outerHeight+" | VIEWPORT: "+a.innerWidth+" x "+a.innerHeight,"green")})}function resizeBrowser(){var a=this.id.replace(/resize-/,"").split("x");chrome.windows.getCurrent(function(b){chrome.windows.update(b.id,{width:parseInt(a[0],10),height:parseInt(a[1],10)},function(){window.close()})})}
function customSize(){var a=parseInt($("custom-size-width").value,10),b=parseInt($("custom-size-height").value,10);chrome.windows.getCurrent(function(c){chrome.windows.update(c.id,{width:parseInt(a,10),height:parseInt(b,10)},function(){window.close()})})}function validateHTML(){isSupportedURL()&&fileSchemeAllowed(!1)&&openTab(oOptions.url_validate_html+oCurrentTab.url)}function validateCSS(){isSupportedURL()&&fileSchemeAllowed(!1)&&openTab(oOptions.url_validate_css+oCurrentTab.url)}
function checkLinks(){isSupportedURL()&&fileSchemeAllowed(!1)&&openTab(oOptions.url_validate_links+oCurrentTab.url)}function validateFeed(){isSupportedURL()&&fileSchemeAllowed(!1)&&openTab(oOptions.url_validate_feed+oCurrentTab.url)}function validateAccessibility(){isSupportedURL()&&fileSchemeAllowed(!1)&&openTab(oOptions.url_validate_accessibility+oCurrentTab.url)}
function validateLocalHTML(){isSupportedURL()&&fileSchemeAllowed(!1)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"retrieveHTML"},function(a){oBkgPage.createTab("created-tabs/validate-local-html.html",a)})}function validateLocalCSS(){isSupportedURL()&&fileSchemeAllowed(!1)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:"retrieveCSS"},function(a){oBkgPage.createTab("created-tabs/validate-local-css.html",a)})}
function isSupportedURL(){if(oCurrentTab.url.substr(0,36)==="https://chrome.google.com/extensions")return showNotification("THIS FEATURE DOES NOT WORK ON THE CHROME EXTENSION GALLERY","red"),!1;else if(oCurrentTab.url.substr(0,34)==="https://chrome.google.com/webstore")return showNotification("THIS FEATURE DOES NOT WORK ON THE CHROME WEB STORE","red"),!1;return!0}
function fileSchemeAllowed(a){if(a&&oCurrentTab.url.substr(0,7)==="file://")return!0;else if(oCurrentTab.url.match(/^https?:\/\//i))return!0;showNotification("THIS FEATURE DOES NOT WORK WITH THIS URL SCHEME","red");return!1}function openTab(a){chrome.tabs.create({url:a,index:oCurrentTab.index+1})}
function showNotification(a,b){var c=$("notification");c.innerText=a;c.style.display="block";c.className=b;clearTimeout(iNotificationTimeoutId);iNotificationTimeoutId=setTimeout("$('notification').style.display='none';",3E3)}function toggleFeature(a,b){isSupportedURL()&&fileSchemeAllowed(!0)&&chrome.tabs.sendRequest(oCurrentTab.id,{sMethod:b},function(){oBkgPage.toggleFeatureState(a.id,oCurrentTab.id);a.toggleClass("activated")})}
Element.prototype.hasClass=function(a){return this.className.search("(^|\\s)"+a+"(\\s|$)")!==-1};Element.prototype.addClass=function(a){this.hasClass(a)||(this.className+=" "+a)};Element.prototype.removeClass=function(a){this.className=this.className.replace(RegExp("(^|\\s)"+a+"(?:\\s|$)"),"$1")};Element.prototype.toggleClass=function(a){this.hasClass(a)?this.removeClass(a):this.addClass(a)};function $(a){return document.getElementById(a)}document.addEventListener("DOMContentLoaded",init,!1);